<h3>CSS Fonts</h3>
<p class='verdana'>
Lorem ipsum dolor sit amet, consectetur adipiscing elit. Aliquam placerat urna id augue porttitor pellentesque. Aliquam ac gravida tortor, non tempus magna. Fusce sed erat luctus, vestibulum justo in, scelerisque felis. Vivamus ac nisi convallis, viverra arcu non, imperdiet est. Etiam hendrerit facilisis mauris, ut aliquam turpis rutrum id. Aenean laoreet orci sapien, eget molestie ligula elementum eget. Etiam faucibus risus metus, sed sodales lectus tincidunt sed.
</p>
<p class='times-roman'>
Nullam vel suscipit diam. Vivamus vel erat eget eros ullamcorper fermentum. Ut a sem eget sem vehicula lacinia ut sagittis libero. Donec maximus laoreet neque, nec tristique mi consectetur vitae. Sed non sapien venenatis, commodo ligula eget, posuere purus. Pellentesque odio eros, aliquam eget dui ac, commodo mattis risus. Suspendisse eget lobortis diam. Nunc eu odio hendrerit, venenatis orci eget, placerat ipsum.
</p>
<p class='arial'>
In euismod mauris eu nisi porta malesuada. Aliquam erat volutpat. Nulla iaculis ante id lectus auctor fermentum at non sapien. Aliquam tincidunt massa a sem lacinia pharetra. In pellentesque blandit orci, vitae iaculis dolor tincidunt sed. Donec eget purus aliquet, euismod ipsum nec, accumsan lacus. Aenean magna orci, fringilla eget quam eget, feugiat condimentum elit. Nam auctor vel justo quis tristique.
</p>
<p class='bauhaus-93'>
Integer et justo urna. Nullam vitae mauris ultrices, vehicula quam vitae, tempus eros. Nulla ut turpis ac tortor ornare pulvinar non nec ipsum. Pellentesque gravida ex purus, eu commodo magna sodales eget. Pellentesque porttitor accumsan enim vitae tempus. Nam scelerisque dapibus felis, eget cursus ante fermentum vitae. Vivamus pharetra, leo et volutpat commodo, sapien dolor placerat leo, a vulputate sem mi a tellus. Donec finibus placerat magna, et egestas lectus sagittis sed. Quisque venenatis nunc vitae mattis congue. Etiam nec lectus ex. Nam hendrerit nisi eget nunc molestie, a sollicitudin urna ullamcorper. Sed in elit venenatis, ultrices lorem quis, sollicitudin ipsum. Interdum et malesuada fames ac ante ipsum primis in faucibus. Nam rhoncus ante id nisl pharetra, sed tempor ipsum consectetur. Nam malesuada velit ac diam pellentesque varius.
</p>
<p>
Phasellus lectus massa, accumsan in nulla quis, placerat tempor ante. Duis non volutpat risus. Duis ac luctus magna, dignissim dignissim nunc. Nunc et metus volutpat, faucibus dui ac, sollicitudin tortor. Donec pharetra justo ipsum, in blandit elit pulvinar ut. Ut sagittis nulla eu libero viverra, nec aliquet dui congue. Class aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos himenaeos. Praesent dictum ligula eget tempus gravida. In blandit gravida sodales. Donec suscipit fermentum viverra. Suspendisse urna orci, porttitor eu commodo sed, imperdiet in orci. Aliquam at massa sit amet augue consequat ullamcorper non nec urna. Nunc sagittis convallis elit, in luctus est. Praesent consequat lectus ac lobortis placerat. Pellentesque tempus quis ex vitae luctus. Praesent sollicitudin malesuada sem ac aliquam.
</p>